<?php


namespace app\api\model;


use think\Exception;
use think\facade\Cache;
use think\Model;

class AttrText extends Model
{
    protected $table = 'wk_attr_text';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $value
     * @return \think\response\Json
     * 添加属性值
     */
    public function add($value){
        try {
            $this->allowField(true)->save($value);
            $this->table(ATTR_LINK)->insert(['text_id' => $this->id, 'attr_id' => $value['attr_id']]);
            Cache::rm('attr_arr');
            $attrModel = new attr();
            $attrModel->SelectAttrText();
            return ['data'=>['text_id' => $this->id],'code'=>0];
        }catch (Exception $e){
            return ['data'=>$e->getMessage(),'code'=>1005];
        }
    }

    /**
     * @param $text_id
     * @return string 商品ID ','拼接
     * 通过属性查找商品
     */
    public function goodsTextFind($text_id){
//        $goods_id = '';
        for ($i=0;$i<count($text_id);$i++){
            $whereLink[] = ['text_id','=',$text_id[$i]];
            if (!empty($goods_id)){
                $whereLink[] = ['goods_id','in',$goods_id];
            }
            $goods_id = implode(',',array_unique($this->table(ATTR_TEXT_GOODS_LINK)->where($whereLink)->column('goods_id')));
            unset($whereLink);
        }
        return $goods_id;
    }
}