<?php


namespace app\api\model;


use think\Exception;
use think\facade\Cache;
use think\Model;

class AttrText extends Model
{
    protected $table = 'wk_attr_text';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $value
     * @return \think\response\Json
     * 添加属性值
     */
    public function add($value){
        try {
            $this->allowField(true)->save($value);
            $this->table(ATTR_LINK)->insert(['text_id' => $this->id, 'attr_id' => $value['attr_id']]);
            Cache::rm('attr_arr');
            $attrModel = new attr();
            $attrModel->SelectAttrText();
            return ['data'=>['text_id' => $this->id],'code'=>0];
        }catch (Exception $e){
            return ['data'=>$e->getMessage(),'code'=>1005];
        }
    }


}