<?php
namespace app\api\Model;
use think\Exception;
use think\Model;
use think\Validate;

class Goods extends Model
{
    public $rule;
    public $msg;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->rule = [
            'name' => 'require|max:25',
            'id' => 'number|between:1,25',
        ];
        $this->msg = [
            'name.require' => '名称必须',
            'name.max'     => '名称最多不能超过25个字符',
            'id.between'     => 'ID必须在1-25之间',
        ];
    }

    public function findOne($id){
        return $this->where('id',$id)->find();
    }
    public function add($post){
        $validate   = Validate::make($this->rule,$this->msg);
            if (!$validate->check($post)){
                die($validate->getError());
            }else{
                return ret();
            }



    }

}