<?php
namespace app\api\controller;
use app\api\model\Attr;
use app\api\model\Client;
use app\api\model\Unit;
use think\Controller;
use think\facade\Cache;
use think\facade\Session;

class Base extends Controller
{
    public $api_token ;
    public $attr ;
    public $unit ;
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
//        $this->api_token = md5(API_SECRET.date('Ymd',time()));
//        Cache::set('api_token',$this->api_token,60*60*24);
        //初始化所有缓存数组
        $this->attr = new Attr();
        $this->attr->SelectAttrText();
        $this->unit = new Unit();
        $this->unit->SelectUnit();
    }

    public function requset_post($post_arr = [])
    {
        $post = $this->request->post();

        if (!empty($post)) {
            if (!empty($post_arr)) {
                //验证参数名称是否正确
                for ($i = 0; $i < count($post_arr); $i++) {
                    if (!isset($post[$post_arr[$i]])) {
                        return false;
                    }
                }
            }
            return $post;
        } else {
            return false;
        }
    }
    public function requset_get($get_arr)
    {
        $get = $this->request->get();
        if (!empty($get)) {
            if (!empty($get_arr)) {
                //验证参数名称是否正确
                for ($i = 0; $i < count($get_arr); $i++) {
                    if (!isset($get[$get_arr[$i]])) {
                        return false;
                    }
                }
            }
            return $get;
        } else {
            return false;
        }
    }
    public function check_token($app_token){

        if (!empty($app_token)) {

                if ($app_token === $this->api_token) {
                return '验证成功';
                } else {
                    return ret('apptoken验证失败', 1101);
                }

        }else{
            return ret('接口异常',1001);
        }
    }

    public function upload_file($file){
        $url = '';
        if ($file['image']['error'] == 0) {
            $files = request()->file('image');
            // 移动到框架应用根目录/uploads/ 目录下
            $info = $files->move('../public/static/uploads/');
            if ($info) {
                $url =  str_replace("\\", "/", '/haifei/public/static/uploads/' . $info->getSaveName());
            }
        }
        return $url;
    }

}