<?php
namespace app\api\controller;
use think\Controller;
use think\facade\Session;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 验证用户
     */
    protected function check_login($user_id)
    {
        if (Session::has('user_name') && Session::has('user_id')) {
            if (Session::get('user_id') === $user_id) {
                return true;
            } else {
//                return false;
                return true;
            }
        } else {
//            return false;
            return true;
        }
    }

    public function requset_post($post_arr = [])
    {
        $post = $this->request->post();
//        if (empty($post)){
//            $post =  json_decode(file_get_contents('php://input'),true);
//        }
        if (!empty($post)) {
            if (!empty($post_arr)) {
                //验证参数名称是否正确
                for ($i = 0; $i < count($post_arr); $i++) {
                    if (!isset($post[$post_arr[$i]])) {
                        return false;
                    }
                }
            }
            return $post;
        } else {
            return false;
        }
    }

    public function requset_get($get_arr)
    {
        $get = $this->request->get();
        if (!empty($get)) {
            if (!empty($get_arr)) {
                //验证参数名称是否正确
                for ($i = 0; $i < count($get_arr); $i++) {
                    if (!isset($get[$get_arr[$i]])) {
                        return false;
                    }
                }
            }
            return $get;
        } else {
            return false;
        }
    }
}