<?php
//安装单元测试  测试company_save

namespace app\api\controller;

use app\api\model\Company as companyModel;
use app\api\model\Attr;
use app\api\model\Log;

class Company extends Base
{
    public $companyModel;
    public $attrModel;
    public $logModel;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->companyModel = new companyModel();
        $this->attrModel = new Attr();
        $this->logModel = new Log();
    }


    /**
     * @return \think\response\Json
     * 单公司新增/修改
     */
    public function company_save(){
        $param = $this->request->param();
        //简单判断参数，参数类型
        if (array_key_exists('companyData',$param) && array_key_exists('type',$param) && !empty($param['companyData']['attr_info']) && !empty($param['companyData']['image_url']) && is_array($param['companyData']['attr_info'])){
            if ($param['type'] == 'update'){
                //修改
                $CAdata = $this->companyModel->companyEdit($param['companyData']);
                $log['crud'] = 'u';
            }elseif ($param['type'] == 'create') {
                //新增
                $CAdata = $this->companyModel->companyAdd($param['companyData']);
                $log['crud'] = 'c';
             }else{
                return ret('参数错误',1004);
            }

              if ($CAdata['code'] == 0){
                  //添加公司-属性关联
               $CALdata =  $this->companyModel->companyAttrLink($param['companyData']['attr_info'],$CAdata['data']);
               if (!empty($CALdata['data']) && $CALdata['code'] == 0){
                   //添加图片(暂无) 云资源数据库还是本地数据库
                   $CPAdata =  $this->companyModel->companyPicAdd($param['companyData']['image_url'],$CAdata['data']);
                   if ($CPAdata['code'] == 0){
                       //添加日志
                       $log['user_id'] = $GLOBALS['admin_id'];
                       $log['user_name'] = $GLOBALS['admin_name'];
                       $log['table_name'] = COMPANY;
                       $log['table_id'] = $CAdata['data'];
                       $this->logModel->createLog($log);
                       return ret('操作成功');
                   }else{
                       //图片更新失败
                       return ret($CPAdata['data'].',图片更新失败',$CPAdata['code']);
                   }
               }else{
                     $this->companyModel->companySaveOne($CAdata['data'],'is_del',2);
                   return ret($CALdata['data'],$CALdata['code']);
               }
              }else{
                  return ret($CAdata['data'],$CAdata['code']);
              }
        }
        return ret('参数错误',1004);
    }

    public function company_list(){
        $param = $this->request->param();

            if (array_key_exists('text_id',$param) && is_array($param['text_id'])) {
                $c_id = $this->companyModel->companyAttrFind($param['text_id']);
                if (!empty($param['where'])) {
                    $param['where'] .= '--id|in|' . $c_id;
                }else{
                    $param['where'] = 'id|in|' . $c_id;
                }
            }

           $CLdata =  $this->companyModel->companyList($param['where']??'',$param['id']??0);
            if ($CLdata['code'] == 0){
                return ret($CLdata['data'],$CLdata['code']);
            }



    }

}