<?php


namespace app\api\controller;
 use app\api\model\House as houseModel;
 use think\Exception;

 class House extends Base
{
    public $houseModel;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->houseModel = new houseModel();
    }
    public function house_list(){
        $param = $this->request->param();
       $HLdata = $this->houseModel->houseList($param['where']??'',$param['id']??'',$param['subarea']??1);
       if ($HLdata['code'] == 0){
           return ret($HLdata['data']);
       }else{
           return ret($HLdata['data'],$HLdata['code']);
       }
    }
    public function house_save(){
        $param = $this->request->param();
        try {
            if (array_key_exists('houseData', $param) && array_key_exists('type', $param)) {
                if ($param['type'] == 'create') {
                    $HSdata = $this->houseModel->houseAdd($param['houseData']);
                } elseif ($param['type'] == 'update') {
                    $HSdata = $this->houseModel->houseEdit($param['houseData']);
                }

                if (!empty($HSdata)) {
                    if ($HSdata['code'] == 0) {
                        return ret($HSdata['data']);
                    }else{
                        return ret($HSdata['data'],$HSdata['code']);
                    }
                }
            }
            return ret('参数错误', 1004);
        }catch (Exception $e){
            return ret($e->getMessage(),1005);
        }
    }
}