<?php


namespace app\api\controller;


use app\api\model\SendSheet;

class Send extends Base
{
    public $sendModel;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->sendModel = new SendSheet();
    }

    //新增配送单
    public function send_sheet_save(){
        $param = $this->request->param();
        if (array_key_exists('sendData',$param) && array_key_exists('type',$param)){
            if ($param['type'] == 'create'){
                //新增
                $SAdata = $this->sendModel->sendAdd($param['sendData']);
            }
//            elseif($param['type'] == 'update'){
//                //更新
//            }
            else {
                return ret('参数 type 错误', 1004);
            }
            return ret($SAdata['data'],$SAdata['code']);
        }else{
            return ret('参数错误',1004);
        }
    }

    public function send_sheet_list(){
        $param = $this->request->param();
        $req = $this->sendModel->sendList($param['id']??'',$param['send_sn']??'',$param['company_id']??'',$param['staff_id']??'',$param['start_time']??'',$param['end_time']??'',$param['text_id']??[]);
        return ret($req['data'],$req['code']);
    }
}